### ISSUE TITLE
No funciona dev 0.1.4

### ISSUE THREAD

**Issue by j-lml** [Ingobernable/kaos155#27]
He probado en `dev` y no funciona (si funciona en `master`)

```
kaos155 App - version -0.1.4.
MySQL IP:localhost
PROCESS:BORME
Anyo:2009
module.js:538
    throw err;
    ^

Error: Cannot find module './node_app/SCRAP/scr_borme.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.SCRAP (/home/data/projects/kaos155/App/app.js:165:33)
    at /home/data/projects/kaos155/App/app.js:273:60
    at /home/data/projects/kaos155/App/app.js:132:21
    at module.exports (/home/data/projects/kaos155/App/node_app/sql_common.js:2:5)
    at Object.init (/home/data/projects/kaos155/App/app.js:129:52)
    at /home/data/projects/kaos155/App/app.js:273:21 
```

**Comment by j-lml** [comment]
un fallo se da por MAY/min
el otro porque hay alguna ruta que apunta a utils en lugar de _utils
Ahora hago un pull request

**Comment by j-lml** [comment]
enviado pull request

**Comment by j-lml** [comment]
pull request aceptado issue #27
