### ISSUE TITLE
Falla BOCM 2011

### ISSUE THREAD

**Issue by j-lml** [Ingobernable/kaos155#29]
Ya había terminado BOE (BOE correcto) pero me falla en BOCM

He lanzado varios años al mismo tiempo y ahora solo me funciona el 2017
Aparte del fallo, ¿hay forma de poder forzar a que rehaga el proceso sin borrar TODAS las tablas?

**nota**: me da el mismo fallo en varios años

```node app.js SCRAP BOCM 2011
```

```kaos155 App - version -0.1.4.
MySQL IP:localhost
PROCESS:BOCM
Anyo:2011
new connection BOCM mysql OK
ERROR http://w3.bocm.es/boletin/CM_Boletin_BOCM/2011/01/01/BOCM-20110101.PDF
delay ok.
/home/data/projects/kaos155/App/node_app/_common.js:183
                                if (data._list.length > 0) {
                                               ^

TypeError: Cannot read property 'length' of undefined
    at /home/data/projects/kaos155/App/node_app/_common.js:183:48
    at /home/data/projects/kaos155/App/node_app/_common.js:84:37
    at /home/data/projects/kaos155/App/node_app/scrap/scr_bocm.js:145:25
    at Timeout._onTimeout (/home/data/projects/kaos155/App/node_app/func_common.js:53:29)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) 
```

**Comment by Softman65** [comment]
CALL `bbdd_kaos155_text`.`DropTextFromYear`(<{_from_year int}>, <{_to_year
int}>, <{_type nvarchar(7)}>);

borra los textos del scrap desde un año hasta otro y el tipo de proceso
BORME BOE o BOCM

2018-01-11 8:54 GMT+01:00 j-lml <notifications@github.com>:
